spring.application.name=lexilearn

spring.datasource.url=jdbc:h2:mem:lexilearn
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciBsZXhpbGVhcm4gYXBwbGljYXRpb24=
app.jwt.expiration-ms=86400000
